"""Assemble the V8 publication report and reproducibility package.

Reads the frozen V4/V5/V6/V7 artifacts, composes the manuscript tables (from
:mod:`validation.tables`) and figure references (from :mod:`validation.figures`) into
``VALIDATION_AND_BENCHMARKING.md``, and gathers a reproducibility bundle. **No numbers
are computed here** — the report is a presentation of frozen, tested results. Nothing
imports ``mechanism``.
"""
from __future__ import annotations

import os
from typing import Optional

from ._artifacts import (
    load_sweep_records, load_sweep_manifest, load_method_comparison,
    results_digest_of,
)
from . import tables as _tables


def _section_intro(manifest: dict, digest: str) -> str:
    systems = ", ".join(manifest["systems"])
    return (
        "# STRIDE — Validation and Benchmarking\n\n"
        "This report is generated by the V8 publication layer from the **frozen** "
        "V7 results store and the V4/V5/V6 artifacts. It introduces no new numbers: "
        "every value is read from a persisted, tested artifact.\n\n"
        f"- Systems exercised: {systems} "
        f"({manifest['n_non_denv_systems']} beyond DENV)\n"
        f"- Sweep cells: {manifest['n_cells']}; per-cell evaluations: "
        f"{manifest['n_eval']}\n"
        f"- Validation version: {manifest['validation_version']}\n"
        f"  (data-provenance version — the release that produced the frozen store)\n"
        f"- Results-store digest: `{digest}`\n\n"
        "Scope (honest): synthetic ground truth is the correct instrument for "
        "operating characteristics — the true reproducible scale is unknowable on "
        "real data. Biological generality is a separate, later step and is **not** "
        "claimed here.\n"
    )


def _section_calibration(artifact_dir: Optional[str]) -> str:
    return ("\n## Calibration (Part V step 11)\n\n"
            "Empirically calibrated reproducibility thresholds rho* (upper-alpha "
            "surrogate-null quantile), per system and replicate count.\n\n"
            + _tables.table_calibration(artifact_dir).to_markdown()
            + "\n![calibration curve](figures/fig_calibration_curve.png)\n")


def _section_emp_vs_pred(artifact_dir: Optional[str]) -> str:
    return ("\n## Empirical vs predicted operating characteristics (Part IV)\n\n"
            "Empirical FPR/power at the calibrated rho* paired with the V3 predicted "
            "closed form. FPR is controlled at alpha; power agrees at moderate/high "
            "SNR and diverges at low SNR — an honest characterization of the current "
            "estimator, not a tuned result.\n\n"
            + _tables.table_empirical_vs_predicted(artifact_dir).to_markdown()
            + "\n![empirical vs predicted](figures/fig_empirical_vs_predicted.png)\n")


def _section_baselines(artifact_dir: Optional[str]) -> str:
    c = load_method_comparison(artifact_dir)
    bh = c.get("benjamini_hochberg", {})
    n_rej = bh.get("n_rejected", "n/a")
    n_claims = len(bh.get("pvals", []) or [])
    return ("\n## Baseline comparison and the Part VII consequence\n\n"
            "On planted nulls, STRIDE refuses the over-resolution that "
            "single-trajectory and naive-ensemble practice emit; paired McNemar and "
            "bootstrap tests quantify the gap.\n\n"
            + _tables.table_over_resolution(artifact_dir).to_markdown()
            + f"\nAcross the pre-registered comparisons, Benjamini-Hochberg rejects "
              f"{n_rej} of {n_claims} at alpha=0.05.\n\n"
            + _tables.table_coverage(artifact_dir).to_markdown()
            + "\n![over-resolution comparison]"
              "(figures/fig_over_resolution_comparison.png)\n"
            + "\n![coverage](figures/fig_coverage.png)\n"
            + "\n*Limitation:* full ROC/PR curves are not reconstructible from the "
              "frozen store (it records over-resolution rates and paired statistics, "
              "not per-item score vectors); the separation summary above is shown "
              "instead.\n")


def _section_ell_min(artifact_dir: Optional[str]) -> str:
    return ("\n## Resolution headline: ell_min (Part IV)\n\n"
            "Predicted finest reproducible scale index over the (K, T) grid.\n\n"
            "![ell_min heatmap](figures/fig_ell_min_heatmap.png)\n"
            "\n*Limitation:* the profile figure is a schematic built from stored "
            "rho* per scale; raw production Pi profiles are not persisted in the "
            "frozen results store.\n"
            "\n![profile schematic](figures/fig_profile_schematic.png)\n")


def _section_hierarchy(artifact_dir: Optional[str]) -> str:
    return ("\n## Hierarchy sensitivity across systems (>= 2 beyond DENV)\n\n"
            "Operating characteristics across distinct hierarchy topologies "
            "(single- vs two-chain; domain- vs chain-scale drivers).\n\n"
            + _tables.table_hierarchy_sensitivity(artifact_dir).to_markdown()
            + "\n![hierarchy sensitivity](figures/fig_hierarchy_sensitivity.png)\n")


# required report sections, in order (used by tests + assembler)
REQUIRED_SECTIONS = (
    "Calibration",
    "Empirical vs predicted",
    "Baseline comparison",
    "ell_min",
    "Hierarchy sensitivity",
)


def build_report_text(artifact_dir: Optional[str] = None) -> str:
    """Assemble the full report markdown from frozen artifacts (no recomputation)."""
    manifest = load_sweep_manifest(artifact_dir)
    digest = results_digest_of(load_sweep_records(artifact_dir))
    parts = [
        _section_intro(manifest, digest),
        _section_calibration(artifact_dir),
        _section_emp_vs_pred(artifact_dir),
        _section_baselines(artifact_dir),
        _section_ell_min(artifact_dir),
        _section_hierarchy(artifact_dir),
        "\n---\n\n*Generated by the STRIDE validation V8 publication layer from a "
        "frozen results store. Reproduce with "
        "`python -m validation report --out <dir>`.*\n",
    ]
    return "".join(parts)


def build_report(out_path: str, *, figures_dir: Optional[str] = None,
                 artifact_dir: Optional[str] = None,
                 render_figures: bool = True) -> str:
    """Write ``VALIDATION_AND_BENCHMARKING.md`` and (optionally) render its figures.

    ``out_path`` is the report markdown path; figures are written under
    ``figures_dir`` (default: ``<report dir>/figures``). Returns the report path.
    """
    out_dir = os.path.dirname(os.path.abspath(out_path))
    fig_dir = figures_dir or os.path.join(out_dir, "figures")
    if render_figures:
        from . import figures as _figures
        _figures.build_all_figures(fig_dir, artifact_dir)
    text = build_report_text(artifact_dir)
    os.makedirs(out_dir, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(text)
    return out_path


def build_package(out_dir: str, *, artifact_dir: Optional[str] = None) -> dict:
    """Build the reproducibility package: report + figures + tables + store copy.

    Returns a manifest dict listing the produced files and the results-store digest,
    so the bundle is self-describing and re-buildable. Deterministic: rebuilding from
    the same frozen store yields identical report/table text and the same file set.
    """
    import shutil

    os.makedirs(out_dir, exist_ok=True)
    fig_dir = os.path.join(out_dir, "figures")
    tab_dir = os.path.join(out_dir, "tables")
    report_path = os.path.join(out_dir, "VALIDATION_AND_BENCHMARKING.md")

    from . import figures as _figures
    fig_paths = _figures.build_all_figures(fig_dir, artifact_dir)
    tab_paths = _tables.write_tables(tab_dir, artifact_dir)
    build_report(report_path, figures_dir=fig_dir, artifact_dir=artifact_dir,
                 render_figures=False)

    # copy the frozen store (reproducibility input) into the bundle, unchanged
    src = artifact_dir or os.path.join(os.path.dirname(__file__), "artifacts")
    store_copy = os.path.join(out_dir, "sweep_results.jsonl")
    shutil.copyfile(os.path.join(src, "sweep_results.jsonl"), store_copy)

    digest = results_digest_of(load_sweep_records(artifact_dir))
    return {
        "report": report_path,
        "figures": fig_paths,
        "tables": tab_paths,
        "results_store": store_copy,
        "results_digest": digest,
    }
